# Part 4.1: Dummy models
Run dummy classifiers and a basic heuristic.

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

train_df = pd.read_parquet('C:\\Users\\Hzaab\\Desktop\\MLSD project\\data\\preprocessed\\train_processed.parquet', engine='fastparquet')
TARGET_COL = 'fake'

X = train_df.drop(columns=[TARGET_COL])
y = train_df[TARGET_COL]

cv = KFold(n_splits=5, shuffle=True, random_state=10)

def evaluate_model(model, X, y, cv):
    scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
    print(f'{model.__class__.__name__} Accuracy: {scores.mean():.4f}')
    return scores


In [5]:
# Model that always outputs the majority class
print('--- Majority Class Dummy ---')
dummy_majority = DummyClassifier(strategy='most_frequent')
evaluate_model(dummy_majority, X, y, cv)

# Model that outputs randomly
print('\n--- Random Dummy ---')
dummy_random = DummyClassifier(strategy='uniform')
evaluate_model(dummy_random, X, y, cv)

# Model with a simple heuristic
print('\n--- Simple Heuristic (Decision Stump) ---')
# Using a decision tree with max_depth=1 as a robust heuristic for splitting on a single feature attribute
heuristic_clf = DecisionTreeClassifier(max_depth=1, random_state=10)
evaluate_model(heuristic_clf, X, y, cv)


--- Majority Class Dummy ---
DummyClassifier Accuracy: 0.8000

--- Random Dummy ---
DummyClassifier Accuracy: 0.5045

--- Simple Heuristic (Decision Stump) ---
DecisionTreeClassifier Accuracy: 0.9445


array([0.945 , 0.935 , 0.95  , 0.96  , 0.9325])

# Part 5 - Model Development
Using 5 fold cross validation on the training set.

## Part 5.1: Simple Models

In [6]:
# Logistic Regression
print('--- Logistic Regression ---')
log_reg = LogisticRegression(max_iter=1000, random_state=10)
evaluate_model(log_reg, X, y, cv)

# Decision Tree
print('\n--- Decision Tree ---')
tree_clf = DecisionTreeClassifier(random_state=10)
evaluate_model(tree_clf, X, y, cv)

# Random Forest
print('\n--- Random Forest ---')
rf_clf = RandomForestClassifier(n_estimators=100, random_state=10)
evaluate_model(rf_clf, X, y, cv)

# K-Nearest Neighbors
print('\n--- K-Nearest Neighbors ---')
knn_clf = KNeighborsClassifier()
evaluate_model(knn_clf, X, y, cv)


--- Logistic Regression ---
LogisticRegression Accuracy: 0.9820

--- Decision Tree ---
DecisionTreeClassifier Accuracy: 0.9755

--- Random Forest ---
RandomForestClassifier Accuracy: 0.9850

--- K-Nearest Neighbors ---
KNeighborsClassifier Accuracy: 0.9755


array([0.9825, 0.975 , 0.98  , 0.9625, 0.9775])

## Part 5.2: ML Models

In [7]:
# Neural Network
print('--- Neural Network ---')
nn_clf = MLPClassifier(random_state=10, max_iter=500)
evaluate_model(nn_clf, X, y, cv)

# XGBoost
print('\n--- XGBoost ---')
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=10)
evaluate_model(xgb_clf, X, y, cv)

# LightGBM
print('\n--- LightGBM ---')
lgbm_clf = LGBMClassifier(random_state=10)
evaluate_model(lgbm_clf, X, y, cv)


--- Neural Network ---
MLPClassifier Accuracy: 0.9850

--- XGBoost ---
XGBClassifier Accuracy: 0.9830

--- LightGBM ---
LGBMClassifier Accuracy: 0.9860


array([0.985 , 0.9875, 0.9925, 0.98  , 0.985 ])